---
- name: R1soft agent installation on new servers 
  hosts: all
  connection: ssh
  tasks: 
    - name: Create Repo file
      when: ansible_os_family == "RedHat" 
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo 
        owner: root
        group: root


    - name: Install Agent 
      when: ansible_os_family == "RedHat" 
      package: 
        name: serverbackup-enterprise-agent 
        state: installed 


    - name: Get Key From Server
      when: ansible_os_family == "RedHat" 
      command: "r1soft-setup --get-key http://{{r1soft_server}}:8080"


    - name: Restart R1soft Agent
      when: (ansible_distribution == "CentOS" and  ansible_distribution_major_version == "6")
      service: 
        name: cdp-agent
        state: restarted 


    - name: Restart R1soft Agent
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      systemd: 
        name: sbm-agent
        state: restarted 





    - name: Install r1soft on Ubuntu
      when: ansible_distribution == "Ubuntu" 
      command: "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list"

    - name: Next command 
      when: ansible_distribution == "Ubuntu" 
      uri: 
        url: http://repo.r1soft.com/r1soft.asc

    - name: Next command 
      when: ansible_distribution == "Ubuntu" 
      command: "apt-key add r1soft.asc" 

    - name: Next command 
      when: ansible_distribution == "Ubuntu" 
      command: "apt-get update"


    
    - name: Install agent 
      when: ansible_distribution == "Ubuntu" 
      apt: 
        name: "r1soft-cdp-enterprise-agent"
        state: present   


    - name: Get Key From Server
      command: "r1soft-setup --get-key http://104.248.112.182:8080"
